print ("Enter your name")
Name = (input("Your name"))
print ("Enter last name")
Surname = (input("Last_name"))
print("I want to wish you great luck in all your endeavors, goals and ideas. I wish you to always stubbornly follow your dreams, easily solve all problems and not turn off the right path. May fate favor you and help you cope with difficulties. May fortune always walk beside you. " + Name + " " + Surname + "!")
